---
version: 9.6.2
slug: ssh
name: Terminal & SSH
description: Allow logging in remotely to Home Assistant using SSH
url: https://github.com/home-assistant/addons/tree/master/ssh
codenotary: notary@home-assistant.io
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
audio: true
hassio_api: true
hassio_role: manager
host_dbus: true
image: homeassistant/{arch}-addon-ssh
ingress: true
init: false
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
  - backup:rw
  - media:rw
options:
  authorized_keys: []
  password: ""
  apks: []
  server:
    tcp_forwarding: false
panel_icon: mdi:console
panel_title: Terminal
ports:
  22/tcp: null
schema:
  authorized_keys:
    - str
  password: password
  apks:
    - str
  server:
    tcp_forwarding: bool
startup: services
uart: true
