# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - zwave/*
pr: none
resources:
  repositories:
    - repository: azure
      type: github
      name: "home-assistant/ci-azure"
      endpoint: "home-assistant"

variables:
  - group: docker

jobs:
  - template: templates/azp-job-addon.yaml@azure
    parameters:
      addon: "zwave"
