---
version: 1.2.0
slug: assist_microphone
name: Assist Microphone
description: Use Assist with local microphone
url: https://github.com/home-assistant/addons/blob/master/assist_microphone
hassio_api: true
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:ro
options:
  awake_wav: "/usr/src/sounds/awake.wav"
  done_wav: "/usr/src/sounds/done.wav"
  sound_enabled: true
  noise_suppression: 0
  auto_gain: 0
  mic_volume_multiplier: 1.0
  sound_volume_multiplier: 1.0
  debug_logging: false
schema:
  awake_wav: str
  done_wav: str
  sound_enabled: bool
  noise_suppression: int
  auto_gain: int
  mic_volume_multiplier: float
  sound_volume_multiplier: float
  debug_logging: bool
audio: true
homeassistant: 2023.12.1
image: homeassistant/{arch}-addon-assist_microphone
