language: bash

sudo: required
service: docker

addons:
  apt:
    packages:
     - docker-ce

before_install:
  - shopt -s globstar
  - docker pull koalaman/shellcheck
  - docker pull stedolan/jq

script:
 - docker run -v $(pwd):/mnt koalaman/shellcheck **/*.sh
 - docker run -v $(pwd):/mnt stedolan/jq < **/*.json '.'

matrix:
  fast_finish: true
