---
version: 1.2.0
slug: ada
stage: deprecated
name: Hey Ada!
description: Voice assistant powered by Home Assistant
url: https://github.com/home-assistant/hassio-addons/blob/master/ada
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
audio: true
homeassistant: 0.102.0
homeassistant_api: true
image: homeassistant/{arch}-addon-ada
init: false
options:
  stt: cloud
  tts: cloud
schema:
  stt: str
  tts: str
