---
version: 1.1.0
slug: speech-to-phrase
name: speech-to-phrase
description: Fast and personalized local speech-to-text
url: http://github.com/OHF-voice/speech-to-phrase
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:rw
backup_exclude:
  - "*/models/*"
homeassistant_api: true
options:
  debug_logging: false
schema:
  debug_logging: bool
ports:
  "10300/tcp": null
homeassistant: 2023.11.0
image: homeassistant/{arch}-addon-speech-to-phrase
