---
version: 3.10.0
slug: check_config
name: Check Home Assistant configuration
description: Check your Home Assistant configuration against other versions
url: https://github.com/home-assistant/hassio-addons/tree/master/check_config
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: manual
image: homeassistant/{arch}-addon-check_config
init: false
map:
  - config
  - ssl
  - media
  - share:rw
options:
  version: stable
schema:
  version: str
startup: once
uart: true
usb: true
