---
version: 2.3.0
slug: whisper
name: Whisper
description: Speech-to-text with Whisper
url: https://github.com/home-assistant/addons/blob/master/whisper
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
backup_exclude:
  - "models*"
options:
  model: tiny-int8
  language: en
  beam_size: 1
  debug_logging: false
schema:
  model: |
    list(turbo|tiny-int8|tiny|tiny.en|base-int8|base|base.en|small-int8|distil-small.en|small|small.en|distil-medium.en|medium-int8|medium|medium.en|large|large-v1|distil-large-v2|large-v2|distil-large-v3|large-v3|custom)
  custom_model: str?
  language: |
    list(auto|af|am|ar|as|az|ba|be|bg|bn|bo|br|bs|ca|cs|cy|da|de|el|en|es|et|eu|fa|fi|fo|fr|gl|gu|ha|haw|he|hi|hr|ht|hu|hy|id|is|it|ja|jw|ka|kk|km|kn|ko|la|lb|ln|lo|lt|lv|mg|mi|mk|ml|mn|mr|ms|mt|my|ne|nl|nn|no|oc|pa|pl|ps|pt|ro|ru|sa|sd|si|sk|sl|sn|so|sq|sr|su|sv|sw|ta|te|tg|th|tk|tl|tr|tt|uk|ur|uz|vi|yi|yo|zh|yue)
  beam_size: int
  initial_prompt: str?
  debug_logging: bool
ports:
  "10300/tcp": null
homeassistant: 2023.8.0.dev20230728
image: homeassistant/{arch}-addon-whisper
