---
version: 0.2.0
slug: whisper
name: Whisper
description: Speech-to-text with Whisper
url: https://github.com/home-assistant/addons/blob/master/whisper
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
options:
  model: tiny-int8
  language: en
  beam_size: 1
schema:
  model: list(tiny-int8|tiny|base|base-int8|small-int8|small|medium-int8)
  language: |
    list(auto|af|am|ar|as|az|ba|be|bg|bn|bo|br|bs|ca|cs|cy|da|de|el|en|es|et|eu|fa|fi|fo|fr|gl|gu|ha|haw|he|hi|hr|ht|hu|hy|id|is|it|ja|jw|ka|kk|km|kn|ko|la|lb|ln|lo|lt|lv|mg|mi|mk|ml|mn|mr|ms|mt|my|ne|nl|nn|no|oc|pa|pl|ps|pt|ro|ru|sa|sd|si|sk|sl|sn|so|sq|sr|su|sv|sw|ta|te|tg|th|tk|tl|tr|tt|uk|ur|uz|vi|yi|yo|zh)
  beam_size: int
ports:
  "10300/tcp": null
homeassistant: 2023.5.0.dev20230418
image: homeassistant/{arch}-addon-whisper
