---
version: 0.29.1
slug: zwave_js
name: Z-Wave JS
description: Control a Z-Wave network with Home Assistant Z-Wave JS
url: https://github.com/home-assistant/addons/tree/master/zwave_js
arch:
  - amd64
  - i386
  - armhf
  - armv7
  - aarch64
discovery:
  - zwave_js
hassio_api: true
homeassistant: 2025.5.0
# image: homeassistant/{arch}-addon-zwave_js
init: false
ingress: true
ingress_port: 8091
ingress_stream: true
map:
  - addon_config:rw
options:
  log_level: info
  log_to_file: false
  log_max_files: 7
  rf_region: Automatic
  soft_reset: Automatic
  s0_legacy_key: ""
  s2_access_control_key: ""
  s2_authenticated_key: ""
  s2_unauthenticated_key: ""
  lr_s2_access_control_key: ""
  lr_s2_authenticated_key: ""
ports:
  3000/tcp: null
  8091/tcp: null
schema:
  device: device(subsystem=tty)?
  socket: str?
  log_level: list(silly|debug|verbose|http|info|warn|error)?
  log_to_file: bool?
  log_max_files: int(1,)?
  rf_region: "list(\
    Automatic|\
    Australia/New Zealand|\
    China|\
    Europe|\
    Europe (Long Range)|\
    Hong Kong|\
    India|\
    Israel|\
    Japan|\
    Korea|\
    Russia|\
    USA|\
    USA (Long Range))?"
  soft_reset: list(Automatic|Enabled|Disabled)?
  s0_legacy_key: match(|[0-9a-fA-F]{32,32})?
  s2_access_control_key: match(|[0-9a-fA-F]{32,32})?
  s2_authenticated_key: match(|[0-9a-fA-F]{32,32})?
  s2_unauthenticated_key: match(|[0-9a-fA-F]{32,32})?
  lr_s2_access_control_key: match(|[0-9a-fA-F]{32,32})?
  lr_s2_authenticated_key: match(|[0-9a-fA-F]{32,32})?
  network_key: match(|[0-9a-fA-F]{32,32})?
  emulate_hardware: bool?
  disable_controller_recovery: bool?
  disable_watchdog: bool?
  safe_mode: bool?
stage: stable
startup: services
timeout: 30
