---
version: 0.3.0
slug: zwave_js
name: Z-Wave JS
description: Control a Z-Wave network with Home Assistant Z-Wave JS
url: https://github.com/home-assistant/addons/tree/master/zwave_js
arch:
  - amd64
  - i386
  - armhf
  - armv7
  - aarch64
codenotary: notary@home-assistant.io
discovery:
  - zwave_js
hassio_api: true
homeassistant: 2021.2.0b0
image: homeassistant/{arch}-addon-zwave_js
init: false
options:
  device: null
  log_level: info
  soft_reset: Automatic
  s0_legacy_key: ""
  s2_access_control_key: ""
  s2_authenticated_key: ""
  s2_unauthenticated_key: ""
ports:
  3000/tcp: null
schema:
  device: device(subsystem=tty)
  log_level: list(silly|debug|verbose|http|info|warn|error)?
  soft_reset: list(Automatic|Enabled|Disabled)?
  s0_legacy_key: match(|[0-9a-fA-F]{32,32})?
  s2_access_control_key: match(|[0-9a-fA-F]{32,32})?
  s2_authenticated_key: match(|[0-9a-fA-F]{32,32})?
  s2_unauthenticated_key: match(|[0-9a-fA-F]{32,32})?
  network_key: match(|[0-9a-fA-F]{32,32})?
  emulate_hardware: bool?
  disable_controller_recovery: bool?
  safe_mode: bool?
stage: stable
startup: services
timeout: 30
