---
version: 4.13.0
slug: letsencrypt
name: Let's Encrypt
description: Manage certificate from Let's Encrypt
url: https://github.com/home-assistant/hassio-addons/tree/master/letsencrypt
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: manual
image: homeassistant/{arch}-addon-letsencrypt
init: false
map:
  - ssl:rw
  - share
options:
  domains:
    - null
  email: null
  keyfile: privkey.pem
  certfile: fullchain.pem
  challenge: http
  dns: {}
ports:
  80/tcp: 80
schema:
  domains:
    - str
  email: email
  keyfile: str
  certfile: str
  challenge: list(dns|http)
  acme_root_ca_cert: str?
  acme_server: url?
  dns:
    aws_access_key_id: str?
    aws_secret_access_key: str?
    azure_config: str?
    cloudflare_api_key: str?
    cloudflare_api_token: str?
    cloudflare_email: email?
    cloudxns_api_key: str?
    cloudxns_secret_key: str?
    digitalocean_token: str?
    directadmin_password: str?
    directadmin_url: str?
    directadmin_username: str?
    dnsimple_token: str?
    dnsmadeeasy_api_key: str?
    dnsmadeeasy_secret_key: str?
    gandi_api_key: str?
    gandi_sharing_id: str?
    gehirn_api_secret: str?
    gehirn_api_token: str?
    google_creds: str?
    hetzner_api_token: str?
    linode_key: str?
    linode_version: str?
    luadns_email: email?
    luadns_token: str?
    netcup_api_key: str?
    netcup_api_password: str?
    netcup_customer_id: str?
    njalla_token: str?
    nsone_api_key: str?
    ovh_application_key: str?
    ovh_application_secret: str?
    ovh_consumer_key: str?
    ovh_endpoint: str?
    propagation_seconds: int(60,3600)?
    provider: "list(dns-azure|dns-cloudflare|dns-cloudxns|dns-digitalocean|\
      dns-directadmin|dns-dnsimple|dns-dnsmadeeasy|dns-gehirn|\
      dns-google|dns-hetzner|dns-linode|dns-luadns|dns-njalla|dns-nsone|dns-ovh|\
      dns-rfc2136|dns-route53|dns-sakuracloud|dns-netcup|dns-gandi|\
      dns-transip|dns-loopia)?"
    rfc2136_algorithm: str?
    rfc2136_name: str?
    rfc2136_port: str?
    rfc2136_secret: str?
    rfc2136_server: str?
    sakuracloud_api_secret: str?
    sakuracloud_api_token: str?
    transip_api_key: str?
    transip_username: str?
    loopia_user: str?
    loopia_password: str?
startup: once
